"""Navigation helpers extracted from build_navigation.py (Phase C).

Kept here so build_navigation.py stays under 200 lines per the spec constraint.
Stdlib only.
"""
from __future__ import annotations

import os

# Files considered navigation/meta — excluded from artifact listings
META_FILES = {"README.md", "DOCUMENT-MAP.md", "DOCUMENT-MAP.draft.md"}

# Sentinel markers for the 2-zone README pattern (RT-F14)
GEN_START = "<!-- generated by rebuild-spec navigation -->"
GEN_END = "<!-- end-generated -->"

# Known artifact filenames → short one-line description
_ARTIFACT_DESCRIPTIONS: dict[str, str] = {
    "overview.md": "Product goals, scope, primary actors, and the big picture — read first",
    "architecture.md": "Layer diagram, tech stack, service boundaries, and the main data flow",
    "business-rules.md": "Invariants and constraints the system must always enforce",
    "entities.md": "Core data entities, their key fields, and how they relate",
    "permissions-matrix.md": "Which role may perform which action (RBAC matrix)",
    "system-overview.md": "High-level system narrative",
    "feature-list.md": "Full feature catalogue (F### entries)",
    "screen-list.md": "Screen inventory (SCR### entries)",
    "screen-flow.md": "Screen navigation / state-transition flows",
    "behavior-logic.md": "Background logic units (BL### entries)",
    "route-list.md": "API route inventory",
    "api-contracts.md": "API contract specifications",
    "api-map.md": "API surface map",
    "data-model.md": "Data model (MODEL### entities)",
    "user-stories.md": "User story catalogue (US### entries)",
    "permissions.md": "Permission / RBAC matrix",
    "crud-matrix.md": "CRUD operations matrix (Phase B extractor)",
    "db-objects.md": "Database object catalogue (Phase B extractor)",
    "component-catalog.md": "Component catalogue (domain / entities / contract / stack / role + dependencies + responsibility per component)",
    "per-component-confidence.md": "Per-component extraction-confidence summary",
    "data-ownership-map.md": "Entity ownership + cross-service correlation + event producer→consumers",
    "cross-service-flows.md": "Cross-service flows / sagas (hybrid: edge skeleton + agent narrative)",
    "spec.md": "Feature technical specification",
    "business-context.md": "Business context and stakeholder view",
    "screens.md": "Screen detail specification",
    "edge-cases.md": "Edge cases and error handling",
    "technical-spec.md": "Technical specification",
    "process-flow.md": "Process flow diagram",
    "glossary.md": "Project glossary",
    "job-list.md": "Batch/background-job inventory (JOB### entries) with schedule and retry detail",
    "design-intent.md": "EXPERIMENTAL: inferred architectural rationale — why the system was built this way",
}


def file_description(name: str) -> str:
    """Return a one-line description for a filename, falling back to a prettified stem."""
    return _ARTIFACT_DESCRIPTIONS.get(name, name.replace("-", " ").replace(".md", ""))


# Per-subdir blurbs: one-line "what is this folder" shown at the top of each leaf README.
# Unknown subdirs fall back to empty string (safe — no crash, no blurb line emitted).
_SUBDIR_BLURBS: dict[str, str] = {
    "system": "Core system-level documentation: architecture, rules, and shared definitions.",
    "generated": "Auto-generated artifacts from rebuild-spec analysis passes.",
    "features": "Per-feature deep-dive specifications (business context, screens, technical spec, edge cases).",
    "screens": "Per-screen detailed UI and behavior specifications.",
    "flows": "Cross-cutting process flows that span more than one feature or service.",
    "components": "Per-component documentation for multi-component / system-of-systems projects.",
}


def subdir_blurb(rel: str) -> str:
    """Return a one-line blurb for a subdir (by its relative name), or '' if unknown."""
    # rel may be a plain name like "system" or a path like "system/subdir"; use the first segment.
    first_segment = rel.split("/")[0].split("\\")[0]
    return _SUBDIR_BLURBS.get(first_segment, "")


def read_user_tail(existing_content: str) -> str:
    """Extract user content below the end-generated marker (RT-F14 preservation)."""
    idx = existing_content.find(GEN_END)
    if idx == -1:
        return ""
    return existing_content[idx + len(GEN_END):]
