"""Helper library for probe_routes.py — LISTERS map, parsers, manifest writer.

Extracted to keep probe_routes.py under 200 lines per project file-size rules.
Stdlib only.
"""
from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# Manifest cap
# ---------------------------------------------------------------------------

# Hard ceiling on manifest route entries.  Probes returning more routes than this
# are almost certainly a CI/staging environment with duplicates or fixture data;
# writing a multi-thousand-row manifest wastes disk and confuses W1 agents.
# When the cap fires, the manifest is truncated and marked with "truncated": true
# so downstream consumers know the list is incomplete.
MAX_MANIFEST_ROUTES = 5000


# ---------------------------------------------------------------------------
# LISTERS map (LOCKED design — do not add install commands)
# ---------------------------------------------------------------------------

# Per-stack lister definitions.
# detect_file: lockfile confirming the stack is present (bootable-first-class).
# detect_binary: local path relative to project root checked via file-exists.
# detect_which: global binary checked via shutil.which.
# cmd: argv list (shell=False always — no user interpolation).
# format: "json" or "text".
LISTERS: dict[str, dict[str, Any]] = {
    "rails": {
        "detect_file": "Gemfile.lock",
        "detect_binary": "bin/rails",
        "cmd": ["bin/rails", "routes"],
        "format": "text",
    },
    "laravel": {
        "detect_file": "composer.lock",
        "detect_binary": None,
        "detect_which": "php",
        "cmd": ["php", "artisan", "route:list", "--json"],
        "format": "json",
    },
    "phoenix": {
        "detect_file": "mix.lock",
        "detect_binary": None,
        "detect_which": "mix",
        "cmd": ["mix", "phx.routes"],
        "format": "text",
    },
    "symfony": {
        # Requires composer.lock AND bin/console: disambiguates from Laravel (which also uses
        # composer.lock but uses artisan as its entrypoint, not bin/console).
        # A composer.lock project without bin/console → laravel classification only.
        "detect_file": ("composer.lock", "bin/console"),
        "detect_binary": "bin/console",
        "cmd": ["php", "bin/console", "debug:router", "--format=json"],
        "format": "json",
    },
    "django": {
        # manage.py is generated by `django-admin startproject` and exists in virtually every
        # Django project regardless of whether dependencies are installed — it is NOT a lockfile
        # and does not confirm bootability. We require manage.py AND a dependency manifest
        # (requirements.txt / pyproject.toml / Pipfile.lock / poetry.lock) so that a bare
        # manage.py skeleton (or a non-Django project that happens to use the same filename)
        # does not trigger the probe gate.
        # detect_file is used by probe_routes.classify_bootable — it checks file existence via
        # Path(project_root / detect_file).is_file(). Django uses a tuple of alternatives;
        # probe_routes.classify_bootable handles tuple detect_file by requiring manage.py AND
        # at least one dep manifest.
        "detect_file": ("manage.py", ("requirements.txt", "pyproject.toml", "Pipfile.lock", "poetry.lock")),
        "detect_binary": None,
        "detect_which": "python3",
        "cmd": ["python3", "manage.py", "show_urls"],
        "format": "text",
    },
}

# Defensive: verify no install commands in any LISTERS entry at import time.
_FORBIDDEN_TOKENS = ("install", "update", "upgrade", "require", "add")
for _stack, _defn in LISTERS.items():
    for _token in _defn.get("cmd", []):
        assert not any(f in _token.lower() for f in _FORBIDDEN_TOKENS), (
            f"LISTERS[{_stack}].cmd contains forbidden install token: {_token!r}"
        )


# ---------------------------------------------------------------------------
# Output parsers
# ---------------------------------------------------------------------------

def parse_json_output(raw: str, stack: str) -> list[dict[str, str]]:
    """Parse JSON lister output (Laravel, Symfony) into normalized route rows."""
    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        return []
    if not isinstance(data, list):
        return []
    routes: list[dict[str, str]] = []
    for item in data:
        if not isinstance(item, dict):
            continue
        method = str(item.get("method", item.get("verb", ""))).upper()
        path = str(item.get("uri", item.get("path", item.get("url", ""))))
        handler = str(item.get("action", item.get("handler", item.get("name", ""))))
        if path:
            routes.append({"method": method, "path": path, "handler": handler, "stack": stack})
    return routes


def parse_text_output(raw: str, stack: str) -> list[dict[str, str]]:
    """Parse plain-text lister output (Rails, Phoenix) heuristically into route rows.

    Rails `bin/rails routes` emits columns: Prefix | Verb | URI Pattern | Controller#Action.
    This parser intentionally ignores the route name/prefix column — Tier-1 manifest only
    needs method/path/handler; the prefix is advisory data not used downstream.
    """
    routes: list[dict[str, str]] = []
    # Known gap: Phoenix LiveView `live` verb lines are not in this set and will not be
    # parsed.  The Tier-1 manifest is advisory; live routes appear in route-list.md instead.
    http_methods = {"GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS", "ANY"}
    for line in raw.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        method = path = handler = ""
        for i, tok in enumerate(parts[:4]):
            upper = tok.upper().strip("│|")
            if upper in http_methods:
                method = upper
                remaining = [p for p in parts[i + 1:] if p not in ("│", "|", "->")]
                if remaining:
                    path = remaining[0]
                if len(remaining) > 1:
                    handler = remaining[1]
                break
        if path:
            routes.append({"method": method, "path": path, "handler": handler, "stack": stack})
    return routes


# ---------------------------------------------------------------------------
# Manifest writer
# ---------------------------------------------------------------------------

def write_manifest(routes: list[dict[str, str]], plan_dir: Path) -> Path:
    """Write route-manifest.json + route-manifest.txt under plan_dir/artifacts/.

    Write order: .txt first (best-effort human-readable companion), then atomic rename of
    .json into place. This ensures that if the rename succeeds the .txt is already present;
    a failure after .txt but before rename leaves no orphaned JSON without its companion.
    JSON is the authoritative artifact; .txt is best-effort and may be stale if regenerated
    without a clean artifacts/ directory.

    When len(routes) > MAX_MANIFEST_ROUTES the list is truncated to MAX_MANIFEST_ROUTES entries.
    The JSON manifest gains "truncated": true and "total_routes": <original count>.
    The .txt manifest gains a warning line at the top.
    Returns path to the JSON manifest.
    """
    artifacts = plan_dir / "artifacts"
    artifacts.mkdir(parents=True, exist_ok=True)

    json_path = artifacts / "route-manifest.json"
    txt_path = artifacts / "route-manifest.txt"

    total_routes = len(routes)
    truncated = total_routes > MAX_MANIFEST_ROUTES
    if truncated:
        routes = routes[:MAX_MANIFEST_ROUTES]

    lines = ["# Route Manifest (Tier-1 CLI probe)", ""]
    if truncated:
        lines.append(
            f"# WARNING: manifest truncated to {MAX_MANIFEST_ROUTES} of {total_routes} routes."
            " Supplement with Tier-2 manual inspection."
        )
        lines.append("")
    lines.append(f"{'Method':<8}  {'Stack':<10}  {'Path':<50}  Handler")
    lines.append("-" * 90)
    for r in routes:
        lines.append(
            f"{r.get('method',''):<8}  {r.get('stack',''):<10}  {r.get('path',''):<50}  {r.get('handler','')}"
        )
    txt_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    manifest_obj: Any = list(routes)  # already truncated above

    fd, tmp = tempfile.mkstemp(dir=str(artifacts), prefix=".rm_tmp_")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            payload: dict[str, Any] = {"routes": manifest_obj}
            if truncated:
                payload["truncated"] = True
                payload["total_routes"] = total_routes
            json.dump(payload if truncated else manifest_obj, f, indent=2)
        os.rename(tmp, str(json_path))
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise

    return json_path
