# layout-exempt: rebuild-spec synthesis renderers — docs/system is this skill's own output target
"""Markdown renderers for Phase D system-synthesis output (mechanical artifacts, v18).

v18 BREAKING: `render_service_catalog` and `render_data_ownership_map` are REMOVED.
Those documents are now produced by template substitution in _synthesis_scout_lib.
The compute they relied on (entity_ownership, event_flows, service_dependencies, fan_in_out)
is now done inside _synthesis_scout_lib.build_scout_facts and exposed via scout-report blocks.

Retained: `render_per_component_confidence` — the one mechanical artifact that Python still
writes directly as a .md file (per the design: "per-component-confidence.md stays mechanical").

Stdlib only.
"""
from __future__ import annotations

from typing import Any

from _system_synthesis_lib import sanitize_field


def render_per_component_confidence(
    digests: list[dict[str, Any]], timestamp: str, snap: str
) -> str:
    lines = [
        "# Per-Component Extraction Confidence", "",
        f"<!-- generated by rebuild-spec synthesize_system — {timestamp} -->",
        f"<!-- snapshot-hash: {snap} -->", "",
        "| Component | Stack | RPC Signals | Topic Signals | Entity Signals | "
        "Confidence | Source SHA |",
        "|-----------|-------|-------------|---------------|----------------|"
        "------------|------------|",
    ]
    for d in sorted(digests, key=lambda x: str(x.get("service", ""))):
        is_reused = d.get("provenance", "extracted") == "docs-derived"
        raw_svc = sanitize_field(d.get("service", ""))
        svc = f"{raw_svc} (reused)" if is_reused else raw_svc
        stack = sanitize_field(d.get("stack", ""))
        n_rpc = len([r for r in d.get("rpc", []) if isinstance(r, dict)])
        n_topic = len([t for t in d.get("topic", []) if isinstance(t, dict)])
        n_entity = len([e for e in d.get("entity", []) if isinstance(e, dict)])
        confidence = sanitize_field(d.get("extraction_confidence", ""))
        if not confidence:
            if is_reused:
                confidence = "docs-derived (no fresh extraction)"
            else:
                total = n_rpc + n_topic + n_entity
                confidence = "high" if total >= 3 else "medium" if total >= 1 else "low"
        sha = sanitize_field(str(d.get("source_sha", ""))[:16])
        lines.append(
            f"| {svc} | {stack} | {n_rpc} | {n_topic} | {n_entity} | {confidence} | {sha}… |"
        )
    lines.append("")
    return "\n".join(lines)
