#!/usr/bin/env python3
"""[GRAPHIFY-INTEGRATION] Generate W1 starting DRAFTS from graphify's graph.json.

Produces machine-true skeletons so W1 researchers VERIFY & COMPLETE instead of building
structure from scratch (LLM-from-scratch demonstrably misses files/classes):
  - data-model-draft.md   : every model-ish class in code, grouped by file, with file:line
                            and inherits relations (EXTRACTED edges only; fields are NOT in
                            the graph -> marked TO-VERIFY for the researcher to fill).
  - architecture-draft.md : module-level Mermaid import graph aggregated from EXTRACTED
                            import edges + module size table.

The drafts are STRUCTURE ONLY — researchers must still satisfy every template section, and
all existing quality gates / reviewer checks stay unchanged.

Usage: graph_to_drafts.py --graph graphify-out/graph.json --outdir <plan>/artifacts/_graph-drafts
Exit 0 on success, 1 on any problem (callers treat drafts as best-effort).
Stdlib only.
"""
from __future__ import annotations
import argparse, collections, json, os, re, sys

MODEL_PATH = re.compile(r"(^|/)(models|schemas|entities|domain|migrations|db)(/|$)")


def is_class_label(label: str) -> bool:
    # identifier-shaped only: rejects docstring/sentence nodes graphify sometimes emits
    return bool(label) and label[0].isupper() and label.isidentifier()


def module_of(path: str) -> str:
    parts = path.replace("\\", "/").split("/")
    return "/".join(parts[:2]) if len(parts) > 1 else parts[0]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--graph", required=True)
    ap.add_argument("--outdir", required=True)
    a = ap.parse_args()

    try:
        g = json.load(open(a.graph, encoding="utf-8"))
    except Exception as e:
        print(f"error: cannot read graph: {e}", file=sys.stderr); return 1
    nodes = g.get("nodes", [])
    links = g.get("links", g.get("edges", []))
    if not nodes:
        print("error: empty graph", file=sys.stderr); return 1

    by_id = {n.get("id"): n for n in nodes}

    def extracted(rel_names):
        for l in links:
            if l.get("relation") in rel_names and str(l.get("confidence", "EXTRACTED")) == "EXTRACTED":
                yield l

    # ---------- data-model draft ----------
    classes = collections.defaultdict(list)  # file -> [(label, line, node_id)]
    for n in nodes:
        sf = n.get("source_file") or ""
        if sf and MODEL_PATH.search(sf) and is_class_label(n.get("label", "")):
            loc = str(n.get("source_location") or "").lstrip("L") or "?"
            classes[sf].append((n["label"], loc, n.get("id")))
    inherits = collections.defaultdict(list)  # node_id -> [parent labels]
    for l in extracted({"inherits"}):
        child, parent = by_id.get(l.get("source")), by_id.get(l.get("target"))
        if child is not None and parent is not None:
            inherits[child.get("id")].append(parent.get("label", "?"))

    dm = ["# Data Model — GRAPH DRAFT (verify & complete)", "",
          "<!-- Generated by graph_to_drafts.py from graphify-out/graph.json.",
          "     STRUCTURE ONLY, machine-walked (every class below exists in code at the given",
          "     file:line; EXTRACTED edges only). Fields/types/constraints are NOT in the graph:",
          "     read each file and fill them. Every TO-VERIFY line must be confirmed against",
          "     source. You must still complete ALL sections of data-model-template.md. -->", ""]
    if not classes:
        dm.append("_(no model-ish classes found in graph — build from template as usual)_")
    for f in sorted(classes):
        dm.append(f"## {f}")
        for label, loc, nid in sorted(classes[f], key=lambda x: int(x[1]) if x[1].isdigit() else 0):
            parents = inherits.get(nid)
            suffix = f" — inherits: {', '.join(parents)}" if parents else ""
            dm.append(f"- class `{label}` (L{loc}){suffix}  <!-- TO-VERIFY: fields/types -->")
        dm.append("")

    # ---------- architecture draft ----------
    mod_edges = collections.Counter()
    for l in extracted({"imports", "imports_from"}):
        s, t = by_id.get(l.get("source")), by_id.get(l.get("target"))
        if s is None or t is None:
            continue
        sm, tm = module_of(s.get("source_file") or ""), module_of(t.get("source_file") or "")
        if sm and tm and sm != tm:
            mod_edges[(sm, tm)] += 1
    mod_size = collections.Counter(module_of(n.get("source_file") or "") for n in nodes if n.get("source_file"))

    def mid(m): return re.sub(r"[^A-Za-z0-9_]", "_", m)

    ar = ["# Architecture — GRAPH DRAFT (verify & complete)", "",
          "<!-- Generated by graph_to_drafts.py. Module-level import graph aggregated from",
          "     EXTRACTED import edges (edge label = number of imports). Use as the basis for",
          "     the architecture Mermaid diagram; verify and add prose/tech-stack per",
          "     architecture-template.md. -->", "",
          "```mermaid", "graph TD"]
    for m, cnt in mod_size.most_common():
        if m:
            ar.append(f"  {mid(m)}[\"{m} ({cnt} symbols)\"]")
    for (sm, tm), c in sorted(mod_edges.items(), key=lambda x: -x[1]):
        ar.append(f"  {mid(sm)} -->|{c}| {mid(tm)}")
    ar += ["```", "", "## Module sizes (symbols in graph)", ""]
    ar += [f"- {m}: {c}" for m, c in mod_size.most_common() if m]
    ar.append("")

    os.makedirs(a.outdir, exist_ok=True)
    open(os.path.join(a.outdir, "data-model-draft.md"), "w", encoding="utf-8").write("\n".join(dm))
    open(os.path.join(a.outdir, "architecture-draft.md"), "w", encoding="utf-8").write("\n".join(ar))
    n_cls = sum(len(v) for v in classes.values())
    print(f"drafts generated: data-model ({n_cls} classes / {len(classes)} files), "
          f"architecture ({len(mod_size)} modules, {len(mod_edges)} edges) -> {a.outdir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
